src/SFA.DAS.RoatpGateway.Web/Controllers/RoatpGatewayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SFA.DAS.RoatpGateway.Domain;
using SFA.DAS.RoatpGateway.Web.Extensions;
using SFA.DAS.RoatpGateway.Web.Infrastructure.ApiClients;
using SFA.DAS.RoatpGateway.Web.Infrastructure.Validation;
using SFA.DAS.RoatpGateway.Web.ModelBinders;
using SFA.DAS.RoatpGateway.Web.Services;
using SFA.DAS.RoatpGateway.Web.Validators;
using SFA.DAS.RoatpGateway.Web.ViewModels;

namespace SFA.DAS.RoatpGateway.Web.Controllers
{
    public class RoatpGatewayController : RoatpGatewayControllerBase<RoatpGatewayController>
    {
        private readonly IGatewayOverviewOrchestrator _orchestrator;
        private readonly IRoatpGatewayApplicationViewModelValidator _validator;
        private readonly IRoatpSearchTermValidator _searchValidator;

        public RoatpGatewayController(IRoatpApplicationApiClient applyApiClient,
                                     IGatewayOverviewOrchestrator orchestrator, IRoatpGatewayApplicationViewModelValidator validator,
                                     IRoatpSearchTermValidator searchValidator,
                                     ILogger<RoatpGatewayController> logger, IRoatpGatewayPageValidator gatewayValidator)
            : base(applyApiClient, logger, gatewayValidator)
        {
            _orchestrator = orchestrator;
            _validator = validator;
            _searchValidator = searchValidator;
        }

        [HttpGet("/Roatp/Gateway/New")]
        public async Task<IActionResult> NewApplications([StringTrim] string searchTerm, string sortOrder, int page = 1)
        {
            if (searchTerm != null)
            {
                var validationResponse = _searchValidator.Validate(searchTerm);

                foreach (var error in validationResponse.Errors)
                {
                    ModelState.AddModelError(error.Field, error.ErrorMessage);
                }
            }

            var applications = await _applyApiClient.GetNewGatewayApplications(ModelState.IsValid ? searchTerm : null, sortOrder);
            var applicationCounts = await _applyApiClient.GetApplicationCounts(ModelState.IsValid ? searchTerm : null);

            var viewModel = new RoatpGatewayDashboardViewModel
            {
                Applications = new PaginatedList<RoatpApplicationSummaryItem>(applications, applications.Count, page, int.MaxValue),
                ApplicationCounts = applicationCounts,
                SelectedTab = nameof(NewApplications),
                SearchTerm = searchTerm,
                SortColumn = null,
                SortOrder = sortOrder
            };

            return View("~/Views/Gateway/NewApplications.cshtml", viewModel);
        }

        [HttpGet("/Roatp/Gateway/InProgress")]
        public async Task<IActionResult> InProgressApplications([StringTrim] string searchTerm, string sortColumn, string sortOrder, int page = 1)
        {
            if (searchTerm != null)
            {
                var validationResponse = _searchValidator.Validate(searchTerm);

                foreach (var error in validationResponse.Errors)
                {
                    ModelState.AddModelError(error.Field, error.ErrorMessage);
                }
            }

            var applications = await _applyApiClient.GetInProgressGatewayApplications(ModelState.IsValid ? searchTerm : null, sortColumn, sortOrder);
            var applicationCounts = await _applyApiClient.GetApplicationCounts(ModelState.IsValid ? searchTerm : null);

            var viewModel = new RoatpGatewayDashboardViewModel
            {
                Applications = new PaginatedList<RoatpApplicationSummaryItem>(applications, applications.Count, page, int.MaxValue),
                ApplicationCounts = applicationCounts,
                SelectedTab = nameof(InProgressApplications),
                SearchTerm = searchTerm,
                SortColumn = sortColumn,
                SortOrder = sortOrder
            };

            return View("~/Views/Gateway/InProgressApplications.cshtml", viewModel);
        }

        [HttpGet("/Roatp/Gateway/Closed")]
        public async Task<IActionResult> ClosedApplications([StringTrim] string searchTerm, string sortColumn, string sortOrder, int page = 1)
        {
            if (searchTerm != null)
            {
                var validationResponse = _searchValidator.Validate(searchTerm);

                foreach (var error in validationResponse.Errors)
                {
                    ModelState.AddModelError(error.Field, error.ErrorMessage);
                }
            }

            var applications = await _applyApiClient.GetClosedGatewayApplications(ModelState.IsValid ? searchTerm : null, sortColumn, sortOrder);
            var applicationCounts = await _applyApiClient.GetApplicationCounts(ModelState.IsValid ? searchTerm : null);

            var viewModel = new RoatpGatewayDashboardViewModel
            {
                Applications = new PaginatedList<RoatpApplicationSummaryItem>(applications, applications.Count, page, int.MaxValue),
                ApplicationCounts = applicationCounts,
                SelectedTab = nameof(ClosedApplications),
                SearchTerm = searchTerm,
                SortColumn = sortColumn,
                SortOrder = sortOrder
            };

            return View("~/Views/Gateway/ClosedApplications.cshtml", viewModel);
        }

        [HttpGet("/Roatp/Gateway/{applicationId}")]
        public async Task<IActionResult> ViewApplication(Guid applicationId)
        {
            var username = HttpContext.User.UserDisplayName();

            var viewModel =
                await _orchestrator.GetOverviewViewModel(new GetApplicationOverviewRequest(applicationId, username));

            if (viewModel is null)
            {
                return RedirectToAction(nameof(NewApplications));
            }
            else if (viewModel.ApplicationStatus == ApplicationStatus.Removed
                    || viewModel.ApplicationStatus == ApplicationStatus.Withdrawn)
            {
                return View("~/Views/Gateway/Application_Closed.cshtml", viewModel);
            }
            else
            {
                switch (viewModel.GatewayReviewStatus)
                {
                    case GatewayReviewStatus.New:
                    case GatewayReviewStatus.InProgress:
                    case GatewayReviewStatus.ClarificationSent:
                        return View("~/Views/Gateway/Application.cshtml", viewModel);
                    case GatewayReviewStatus.Pass:
                    case GatewayReviewStatus.Fail:
                    case GatewayReviewStatus.Rejected:
                        return View("~/Views/Gateway/Application_ReadOnly.cshtml", viewModel);
                    default:
                        return RedirectToAction(nameof(NewApplications));
                }
            }
        }



        [HttpGet("/Roatp/Gateway/Clarification/{applicationId}")]
        public async Task<IActionResult> AskForClarification(Guid applicationId)
        {
            var username = HttpContext.User.UserDisplayName();

            RoatpGatewayClarificationsViewModel viewModel =
                await _orchestrator.GetClarificationViewModel(new GetApplicationClarificationsRequest(applicationId, username));


            if (viewModel is null)
            {
                return RedirectToAction(nameof(NewApplications));
            }

            return View("~/Views/Gateway/AskForClarification.cshtml", viewModel);
        }


        [HttpPost("/Roatp/Gateway/{applicationId}/AboutToAskForClarification")]
        public async Task<IActionResult> AboutToAskForClarification(Guid applicationId, string confirmAskForClarification)
        {
            var username = HttpContext.User.UserDisplayName();
            var viewModel = await _orchestrator.GetClarificationViewModel(new GetApplicationClarificationsRequest(applicationId, username));

            if (viewModel is null)
            {
                return RedirectToAction(nameof(NewApplications));
            }
            else if (string.IsNullOrEmpty(confirmAskForClarification))
            {
                viewModel.ErrorMessages = new List<ValidationErrorDetail>
                {
                    new ValidationErrorDetail("ConfirmAskForClarification",
                        "Select if you are sure you want to ask for clarification")
                };

                viewModel.CssFormGroupError = "govuk-form-group--error";
                return View("~/Views/Gateway/AskForClarification.cshtml", viewModel);
            }
            else if (confirmAskForClarification == "No" || viewModel.GatewayReviewStatus == GatewayReviewStatus.ClarificationSent)
            {
                return RedirectToAction(nameof(ViewApplication), new { applicationId });
            }

            var userId = HttpContext.User.UserId();
            await _applyApiClient.UpdateGatewayReviewStatusAsClarification(applicationId, userId, username);
            var vm = new RoatpGatewayOutcomeViewModel { ApplicationId = applicationId };
            return View("~/Views/Gateway/ConfirmApplicationClarification.cshtml", vm);
        }

        [HttpGet("/Roatp/Gateway/{applicationId}/ConfirmOutcome")]
        public async Task<IActionResult> ConfirmOutcome(Guid applicationId, string gatewayReviewStatus, string gatewayReviewComment, string gatewayReviewExternalComment, int? subcontractingLimit)
        {
            var application = await _applyApiClient.GetApplication(applicationId);
            if (application is null)
            {
                return RedirectToAction(nameof(NewApplications));
            }

            var username = HttpContext.User.UserDisplayName();

src/SFA.DAS.RoatpGateway.Web/Views/Shared/_ApplicationActions.cshtml
@using SFA.DAS.RoatpGateway.Domain;
@model SFA.DAS.RoatpGateway.Web.ViewModels.RoatpGatewayApplicationViewModel



<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <div class="das-actions-box">
            <h2 class="govuk-heading-m">Application actions</h2>

            <p class="govuk-body govuk-body govuk-!-margin-bottom-1">
                @if (Model.IsClarificationsSelectedAndAllFieldsSet && !Model.HasOversightOutcome && Model.GatewayReviewStatus != GatewayReviewStatus.ClarificationSent)
                {
                    <a class="govuk-link govuk-link--no-visited-state" asp-controller="RoatpGateway" asp-action="AskForClarification" asp-route-applicationId="@Model.ApplicationId" asp-route-gatewayReviewStatus="@GatewayReviewStatus.ClarificationSent">Ask for clarification</a>
                }
                else
                {
                    <span class="das-!-color-dark-grey">Ask for clarification</span>
                }
            </p>
            <p class="govuk-body govuk-!-margin-bottom-1">
                @if (!Model.HasOversightOutcome && Model.ApplicationStatus != ApplicationStatus.Withdrawn && Model.ApplicationStatus != ApplicationStatus.Removed)
                {
                    <a class="govuk-link govuk-link--no-visited-state" asp-controller="RoatpGatewayApplicationActions" asp-action="RemoveApplication" asp-route-applicationId="@Model.ApplicationId">Internal removal of application</a>
                }
                else
                {
                    <span class="das-!-color-dark-grey">Internal removal of application</span>
                }
            </p>
            <p class="govuk-body govuk-!-margin-bottom-0">
                @if (!Model.HasOversightOutcome && Model.ApplicationStatus != ApplicationStatus.Withdrawn && Model.ApplicationStatus != ApplicationStatus.Removed)
                {
                    <a class="govuk-link govuk-link--no-visited-state" asp-controller="RoatpGatewayApplicationActions" asp-action="WithdrawApplication" asp-route-applicationId="@Model.ApplicationId">Applicant withdrawal of application</a>
                }
                else
                {
                    <span class="das-!-color-dark-grey">Applicant withdrawal of application</span>
                }
            </p>

        </div>
    </div>
</div>

src/SFA.DAS.RoatpGateway.Web/Views/Shared/_DashboardSearch.cshtml
@model SFA.DAS.RoatpGateway.Web.ViewModels.RoatpGatewayDashboardViewModel

<form class="app-search-form" method="get" asp-action="@Model.SelectedTab" asp-controller="RoatpGateway" novalidate>
    @if (!string.IsNullOrWhiteSpace(Model.SortColumn))
    {
        <input type="hidden" asp-for="SortColumn" />
    }
    @if (!string.IsNullOrWhiteSpace(Model.SortOrder))
    {
        <input type="hidden" asp-for="SortOrder" />
    }
    <div class="govuk-form-group" sfa-anyvalidationerror-class="govuk-form-group--error">
        <label asp-for="SearchTerm" class="govuk-visually-hidden">
            Search
        </label>
        <span class="govuk-error-message" asp-validation-for="SearchTerm"></span>
        <div class="app-search-form__group">
            <input class="govuk-input app-search-form__input" asp-for="SearchTerm" maxlength="50" autocomplete="off" sfa-validation-for="SearchTerm" sfa-validationerror-class="govuk-input--error" />
            <div class="app-search-form__button-wrap">
                <button type="submit" class="govuk-button app-search-form__button" data-disable-on-submit="true">
                    Search
                </button>
            </div>
        </div>
    </div>
</form>

@if (!string.IsNullOrWhiteSpace(Model.SearchTerm) && ViewData.ModelState.IsValid)
{
    <div class="app-search-results-info">
        <p class="app-search-results-info__content">
            Showing results for <span class="app-search-results-info__search-term">@Model.SearchTerm</span>
        </p>
        <a class="govuk-link app-search-results-info__clear-link" asp-action="@(Model.SelectedTab)" asp-controller="RoatpGateway">Clear results</a>
    </div>
}

src/SFA.DAS.RoatpGateway.Web/Views/Shared/_TabList.cshtml
@model SFA.DAS.RoatpGateway.Web.ViewModels.RoatpGatewayDashboardViewModel

<ul class="govuk-tabs__list">
    <li class="govuk-tabs__list-item @(Model.SelectedTab == "NewApplications" ? "govuk-tabs__list-item--selected" : "") ">
        <a class="govuk-tabs__tab" asp-action="NewApplications" asp-controller="RoatpGateway" asp-route-searchTerm="@Model.SearchTerm">
            New (@Model.ApplicationCounts.NewApplicationsCount)
        </a>
    </li>
    <li class="govuk-tabs__list-item @(Model.SelectedTab == "InProgressApplications" ? "govuk-tabs__list-item--selected" : "")">
        <a class="govuk-tabs__tab" asp-action="InProgressApplications" asp-controller="RoatpGateway" asp-route-searchTerm="@Model.SearchTerm">
            In progress (@Model.ApplicationCounts.InProgressApplicationsCount)
        </a>
    </li>
    <li class="govuk-tabs__list-item @(Model.SelectedTab == "ClosedApplications" ? "govuk-tabs__list-item--selected" : "")">
        <a class="govuk-tabs__tab" asp-action="ClosedApplications" asp-controller="RoatpGateway" asp-route-searchTerm="@Model.SearchTerm">
            Outcome  (@Model.ApplicationCounts.ClosedApplicationsCount)
        </a>
    </li>
</ul>

src/SFA.DAS.RoatpGateway.Web/Views/Shared/_ValidationSummary.cshtml
@if (!ViewData.ModelState.IsValid)
{
    <div class="govuk-error-summary" aria-labelledby="error-summary-title" role="alert" tabindex="-1" data-module="govuk-error-summary">
        <h2 class="govuk-error-summary__title" id="error-summary-title">
            There is a problem
        </h2>
        <div class="govuk-error-summary__body">
            <ul class="govuk-list govuk-error-summary__list">
                @foreach (var item in ViewContext.ViewData.ModelState.OrderByDescending(x => "ClarificationResponse".Equals(x.Key)))
                {
                    foreach (var error in item.Value.Errors)
                    {
                        var summaryLink = "#" + item.Key;

                        if (item.Key == "Status") {
                            summaryLink = "#OptionPass";
                        }

                        if (item.Key == "MoveToModeration") {
                            summaryLink = "#OptionYes";
                        }

                        <li><a href="@summaryLink">@error.ErrorMessage</a></li>
                    }
                }
            </ul>
        </div>
    </div>
}